# Generated by Django 4.2.1 on 2023-05-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_remove_answers_user_remove_questions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
